version: "3.8"
services:
  hazelcast:
    # image: hazelcast/hazelcast:5.2.1
    image: hazelcast/hazelcast:4.1.10
    ports:
    - "5701:5701"
  management-center:
    image: hazelcast/management-center:5.2.1
    ports:
    - "8080:8080"
    environment:
    - MC_DEFAULT_CLUSTER=dev
    - MC_DEFAULT_CLUSTER_MEMBERS=hazelcast