version: '3'

services:

  expressjs:
    build:
      context: ./
      dockerfile: Dockerfile
    image: nodejs-docker-example
    container_name: nodejs-docker-example
    restart: unless-stopped
    environment:
      TZ: Asia/Ho_Chi_Minh
    ports:
      - 34567:3000
    networks:
      - internal
networks:
  internal:
